#!/bin/bash
# WordPress Plugin Installation Guide for SphereVista360
# WP-CLI Alternative: Manual Installation Instructions

echo "🔌 WordPress Plugin Installation for SphereVista360"
echo "=================================================="
echo ""
echo "❌ WP-CLI not found on this system"
echo "💡 Using manual installation method instead"
echo ""
echo "🌐 Please visit: https://spherevista360.com/wp-admin/"
echo "📍 Navigate to: Plugins → Add New"
echo ""
echo "🚨 ESSENTIAL PLUGINS (Install in this order):"
echo "1. Wordfence Security        - Search: 'Wordfence Security'"
echo "2. UpdraftPlus               - Search: 'UpdraftPlus'"  
echo "3. Yoast SEO                 - Search: 'Yoast SEO'"
echo "4. Smush                     - Search: 'Smush'"
echo "5. Contact Form 7            - Search: 'Contact Form 7'"
echo "6. MonsterInsights           - Search: 'MonsterInsights'"
echo ""
echo "⭐ RECOMMENDED PLUGINS (Install after essentials):"
echo "7. W3 Total Cache            - Search: 'W3 Total Cache'"
echo "8. Social Warfare            - Search: 'Social Warfare'"
echo "9. Elementor                 - Search: 'Elementor'"
echo ""
echo "📖 Detailed guide: See PLUGIN_INSTALLATION_GUIDE.md"
echo "🔍 Verify installation: Run ./verify_plugins.sh"
echo ""
echo "✅ Manual installation guide created successfully!"
